### ISSUE TITLE
[FUNCTION] 기능구현 table 중복되는 값 업데이트하기

### ISSUE THREAD

**Issue by SarahhhC** [youjin9209/2015_software_engineering#9]
viewstudent에서 검색 누를 때마다 매번 값이 추가되는 오류 수정
한번에 한 번씩만 나오도록....

**Comment by SarahhhC** [comment]
굳이 수정 못하면 그대로 두기

**Comment by PYeonHee** [comment]
그리고 한마디 덧붙이자면, Add기능을 수행할 때에, 학생이름이나 학과이름을 한글로 적으면 수행되지 않는데, 이 부분은 ReadME.txt 파일에 '영문으로 입력하도록' 분명히 명시해줘야 하지않을까요? 최종 제출물 정리할 때 참고해야 할 것 같아 comment 합니다.

**Comment by SarahhhC** [comment]
수정 못함...
